name: "Build"
defaults:
  run:
    shell: bash
env:
  SOURCE_DOCKER_REGISTRY: amazon
  SOURCE_DOCKER_IMAGE_NAME: aws-cli
  TARGET_DOCKER_REGISTRY: hazelops
  TARGET_DOCKER_IMAGE_NAME: aws-cli

on:
  schedule:
    - cron: '0 3 * * *'

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest tag
        run: |
          echo "TAG=$(curl -s https://registry.hub.docker.com/v2/repositories/${SOURCE_DOCKER_REGISTRY}/${SOURCE_DOCKER_IMAGE_NAME}/tags | jq -r '.results | sort_by(.id) | reverse | .[0] | .name')" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build -t $TARGET_DOCKER_REGISTRY/$TARGET_DOCKER_IMAGE_NAME:$TAG -t $TARGET_DOCKER_REGISTRY/$TARGET_DOCKER_IMAGE_NAME:latest --build-arg DOCKER_REGISTRY=$SOURCE_DOCKER_REGISTRY --build-arg DOCKER_IMAGE_NAME=$SOURCE_DOCKER_IMAGE_NAME --build-arg TAG=$TAG .

      - name: Push
        run: |
          docker push $TARGET_DOCKER_REGISTRY/$TARGET_DOCKER_IMAGE_NAME:$TAG
          docker push $TARGET_DOCKER_REGISTRY/$TARGET_DOCKER_IMAGE_NAME:latest
